# Generated by Django 4.2.6 on 2023-10-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix360core", "0002_conversion_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="mime_type",
            field=models.CharField(default="application/octet-stream", max_length=256),
        ),
    ]
